server:
  port: 8088

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    
application:
  security:
    jwt:
      secret-key: cq1y2lrmFdifjk8GgqR9kEv8S5jgFoTGDIzeci8edwA=
      expiration: 86400000
    admin:
      username: admin
      password: admin
  file:
    uploads:
      baseFolder: ./uploads